---
title: "R Notebook"

---

```{r}
library(tidyverse)
library(purrr)
library(dplyr)
library(data.table)
library(readxl)
library(ggplot2)
library(ggpubr)
library(ggrepel)
library(patchwork)
```

# Import & Organize Stimuli
```{r}
# Import
stimuli<-read_excel("../stimuli/660CorpusMasterSheet.xlsx")

# Grab relevant columns, sort by Category, mark and exclude items w/ no category label 
stimuli_clean<-stimuli %>%select(Name, Category) %>% arrange(Category)%>%filter(Category!="NA")

# Split Categories into Separate Files
# Split by category
#stimuli_split <- split(stimuli_clean, stimuli_clean$Category)

# Create main output directory
#dir.create("stimuli_by_category", showWarnings = FALSE)

# Write separate csv files
#for (cat in names(stimuli_split)) {
  # create subfolder for each category
  #dir.create(file.path("stimuli_by_category", cat), showWarnings = FALSE)
  # remove Category column for data processing
  #df_out <- stimuli_split[[cat]][ , !(names(stimuli_split[[cat]]) %in% "Category") ]
 # write.csv(
  #  df_out,
  #  file = file.path("stimuli_by_category", cat, "vocab.csv"),
  #  row.names = FALSE)}

#Lists were then run through get_similarities.py to create semantic matrices, including NxN matrices for calculating interitem similarities and 1xN matrices to get similarity between all items and category label, and also get average similarities for each matrix type (skipping diagonals for average interitem similarity)


```

# Average Similarities

```{r}
#calculate average similarity (ie, how well given item fits in category) from original rating data
stimuli_avg <- stimuli %>%
  select(Name, Category, "Category Norm") %>%
  rename(CategoryNorm = "Category Norm") %>%
  filter(Category != "NA") %>%
  arrange(Category) %>%
  mutate(
    CategoryNorm_scaled = (CategoryNorm - min(CategoryNorm, na.rm = TRUE)) / #min/max scaled fit score for later comparison
      (max(CategoryNorm, na.rm = TRUE) - min(CategoryNorm, na.rm = TRUE))) %>%
  group_by(Category) %>%
  summarize(
    Average_Similarity = mean(CategoryNorm_scaled, na.rm = TRUE),       # scaled mean
    SD_Similarity = sd(CategoryNorm_scaled, na.rm = TRUE),              # scaled SD
    Average_Similarity_raw = mean(CategoryNorm, na.rm = TRUE),          # raw mean
    SD_Similarity_raw = sd(CategoryNorm, na.rm = TRUE)                  # raw SD
  ) %>%
  mutate(Similarity_Type = "Rating")

#import DSM derived item x label similarities for each category & combine into one df
base_dir <- "stimuli_by_category"

item_similarities_long <- list.dirs(base_dir, recursive = FALSE) %>%
  map_dfr(function(cat_path) {
    cat_name <- basename(cat_path)
    file_path <- file.path(cat_path, "USE_semantic_matrix_category_label.csv")
    if (!file.exists(file_path)) {
      message("Skipping ", cat_name)
      return(NULL)}
    # read matrix (row names = label word)
    df <- read.csv(file_path, row.names = 1, check.names = FALSE)
    df %>%
      tibble::rownames_to_column("Label_Word") %>%
      pivot_longer(
        cols = -Label_Word,
        names_to = "Item",
        values_to = "Similarity"
      ) %>%
      mutate(Category = cat_name)
  }) %>%
  select(Category, Item, Similarity)

#import AVERAGED label x item and interitem similarities 
average_similarities<-read.csv("stimuli_by_category/category_average_similarity.csv")%>%rename("Similarity_Type"="Matrix_Type")


#link data
average_similarities_comp<-average_similarities%>%rbind(stimuli_avg%>%select(-Average_Similarity_raw,-SD_Similarity_raw,-SD_Similarity))%>%
  pivot_wider(
    names_from = Similarity_Type,
    values_from = Average_Similarity)
```

# Visualizations

```{r}
#Item-wise distribution of normative ratings across categories
#ID outliers
stimuli_outliers <- stimuli %>%
  filter(Category != "NA") %>%
  group_by(Category) %>%
  mutate(
    Q1 = quantile(`Category Norm`, 0.25, na.rm = TRUE),
    Q3 = quantile(`Category Norm`, 0.75, na.rm = TRUE),
    IQR = IQR(`Category Norm`, na.rm = TRUE),
    lower = Q1 - 1.5 * IQR,
    upper = Q3 + 1.5 * IQR,
    is_outlier = `Category Norm` < lower | `Category Norm` > upper
  ) %>%
  ungroup()

#plot
item_wise_ratings_plot<-stimuli %>%
  filter(!is.na(Category), Category != "NA") %>%
  ggplot(aes(x = Category, y = `Category Norm`, fill = Category)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(width = 0.15, alpha = 0.4, size = 1) +
  coord_flip() + scale_y_reverse()+
  geom_text_repel(
    data = stimuli_outliers %>% filter(is_outlier),
    aes(label = Name),
    size = 3,
    max.overlaps = 50
  ) +
  theme_minimal() + ylab("Category Fit (Poorest Fit -> Best Fit)")+
  theme(legend.position = "none")

item_wise_ratings_plot

#Item wise distribution of label x item similarity across categories (DSM derived)
#ID outliers
interitem_outliers <- item_similarities_long %>%
  filter(Category != "NA") %>%
  group_by(Category) %>%
  mutate(
    Q1 = quantile(`Similarity`, 0.25, na.rm = TRUE),
    Q3 = quantile(`Similarity`, 0.75, na.rm = TRUE),
    IQR = IQR(`Similarity`, na.rm = TRUE),
    lower = Q1 - 1.5 * IQR,
    upper = Q3 + 1.5 * IQR,
    is_outlier = `Similarity` < lower | `Similarity` > upper
  ) %>%
  ungroup()

#plot
itemwise_dsm_plot<-item_similarities_long %>%
  filter(!is.na(Category), Category != "NA") %>%
  ggplot(aes(x = Category, y = `Similarity`, fill = Category)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(width = 0.15, alpha = 0.4, size = 1) +
  coord_flip() +
  geom_text_repel(
    data = interitem_outliers %>% filter(is_outlier),
    aes(label = Item),
    size = 3,
    max.overlaps = 50
  ) +
  theme_minimal() +
  theme(legend.position = "none")

itemwise_dsm_plot

#Distribution of average category fit ratings
from_ratings<-stimuli_avg %>% ggplot(aes(x = Category, y = Average_Similarity_raw,fill=Category)) +
  geom_col() +
  geom_errorbar(aes(ymin = Average_Similarity_raw - SD_Similarity_raw,
                    ymax = Average_Similarity_raw + SD_Similarity_raw),
                width = 0.2) + scale_y_reverse()+
  ylim(4,0) + ylab("Avg Fit Rating (Poorest Fit -> Best Fit")+ ggtitle("Ratings Derived")+
  theme_minimal() +theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


#Distribution of average label x item similarities (DSM derived)
from_matrices<-average_similarities_comp %>% mutate(SD_Similarity = sd(Label, na.rm = TRUE))%>% ggplot(aes(x = Category, y = Label,fill=Category)) +
  geom_col() +
  geom_errorbar(aes(ymin = Label - SD_Similarity,
                    ymax = Label + SD_Similarity),
                width = 0.2) +
  ylim(0, 1) + ylab("Avg Label x Item Similarity (Poorest Fit -> Best Fit") + ggtitle("DSM Derived")+
  theme_minimal() +theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

#compare the two averaged distributions
from_ratings+from_matrices

#Correlation between average (scaled) ratings of category fit vs average DSM-derived similarity between label and items
label_correlation<-average_similarities_comp %>%
  ggplot(aes(x = Label, y = Rating, label = Category)) +
  geom_point() + scale_y_reverse()+
  geom_text_repel() + xlab("Avg Category Label x Item Similarity (DSM Derived)") + ylab("Avg Category Fit Rating (Scaled)")+
  geom_smooth(method = "lm", se = FALSE) +
  theme_minimal()

label_correlation
##Note that DSMs arent necessarily equipped for category labeling - similarity is based on similar occurrences in text, and category labels aren't used the same was as individual exemplar names

#Average inter-item similarity across categories
avg_interitem<-average_similarities_comp %>% mutate(SD_Similarity = sd(Interitem, na.rm = TRUE))%>% ggplot(aes(x = Category, y = Interitem,fill=Category)) +
  geom_col() +
  geom_errorbar(aes(ymin = Interitem - SD_Similarity,
                    ymax = Interitem + SD_Similarity),
                width = 0.2) +
  ylab("Avg Interitem Similarity") +
  theme_minimal() +theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

avg_interitem

#Correlation between average (scaled) ratings of item x category fit vs average DSM-derived interitem similarity (cohesion)
interitem_corr<-average_similarities_comp %>%
  ggplot(aes(x = Interitem, y = Rating, label = Category)) +
  geom_point() + scale_y_reverse()+
  geom_text_repel() + xlab("Avg Interitem Similarity (DSM Derived)") + ylab("Avg Category Fit Rating (Scaled)")+
  geom_smooth(method = "lm", se = FALSE) +
  theme_minimal()

interitem_corr

#may be best to choose items based on 1) avg fit between item and category label and 2) Category cohesion (avg interitem similarity)
```


```{r}
